// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/rate/v1/rate.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_proto_rate_v1_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_v1_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rate_v1_rate_proto_rawDescGZIP(), []int{0}
}

type OrderBookEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Volume        string                 `protobuf:"bytes,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Factor        string                 `protobuf:"bytes,4,opt,name=factor,proto3" json:"factor,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookEntry) Reset() {
	*x = OrderBookEntry{}
	mi := &file_proto_rate_v1_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookEntry) ProtoMessage() {}

func (x *OrderBookEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_v1_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookEntry.ProtoReflect.Descriptor instead.
func (*OrderBookEntry) Descriptor() ([]byte, []int) {
	return file_proto_rate_v1_rate_proto_rawDescGZIP(), []int{1}
}

func (x *OrderBookEntry) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderBookEntry) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *OrderBookEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OrderBookEntry) GetFactor() string {
	if x != nil {
		return x.Factor
	}
	return ""
}

func (x *OrderBookEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Asks          []*OrderBookEntry      `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids          []*OrderBookEntry      `protobuf:"bytes,3,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_proto_rate_v1_rate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_v1_rate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rate_v1_rate_proto_rawDescGZIP(), []int{2}
}

func (x *GetRatesResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetRatesResponse) GetAsks() []*OrderBookEntry {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *GetRatesResponse) GetBids() []*OrderBookEntry {
	if x != nil {
		return x.Bids
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_rate_v1_rate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_v1_rate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_rate_v1_rate_proto_rawDescGZIP(), []int{3}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_rate_v1_rate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_v1_rate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_rate_v1_rate_proto_rawDescGZIP(), []int{4}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_rate_v1_rate_proto protoreflect.FileDescriptor

const file_proto_rate_v1_rate_proto_rawDesc = "" +
	"\n" +
	"\x18proto/rate/v1/rate.proto\x12\arate.v1\"\x11\n" +
	"\x0fGetRatesRequest\"\x82\x01\n" +
	"\x0eOrderBookEntry\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x02 \x01(\tR\x06volume\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12\x16\n" +
	"\x06factor\x18\x04 \x01(\tR\x06factor\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"\x8a\x01\n" +
	"\x10GetRatesResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12+\n" +
	"\x04asks\x18\x02 \x03(\v2\x17.rate.v1.OrderBookEntryR\x04asks\x12+\n" +
	"\x04bids\x18\x03 \x03(\v2\x17.rate.v1.OrderBookEntryR\x04bids\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x98\x01\n" +
	"\vRateService\x12?\n" +
	"\bGetRates\x12\x18.rate.v1.GetRatesRequest\x1a\x19.rate.v1.GetRatesResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.rate.v1.HealthCheckRequest\x1a\x1c.rate.v1.HealthCheckResponseB:Z8github.com/your-username/usdt-rate-service/proto/rate/v1b\x06proto3"

var (
	file_proto_rate_v1_rate_proto_rawDescOnce sync.Once
	file_proto_rate_v1_rate_proto_rawDescData []byte
)

func file_proto_rate_v1_rate_proto_rawDescGZIP() []byte {
	file_proto_rate_v1_rate_proto_rawDescOnce.Do(func() {
		file_proto_rate_v1_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rate_v1_rate_proto_rawDesc), len(file_proto_rate_v1_rate_proto_rawDesc)))
	})
	return file_proto_rate_v1_rate_proto_rawDescData
}

var file_proto_rate_v1_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_rate_v1_rate_proto_goTypes = []any{
	(*GetRatesRequest)(nil),     // 0: rate.v1.GetRatesRequest
	(*OrderBookEntry)(nil),      // 1: rate.v1.OrderBookEntry
	(*GetRatesResponse)(nil),    // 2: rate.v1.GetRatesResponse
	(*HealthCheckRequest)(nil),  // 3: rate.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil), // 4: rate.v1.HealthCheckResponse
}
var file_proto_rate_v1_rate_proto_depIdxs = []int32{
	1, // 0: rate.v1.GetRatesResponse.asks:type_name -> rate.v1.OrderBookEntry
	1, // 1: rate.v1.GetRatesResponse.bids:type_name -> rate.v1.OrderBookEntry
	0, // 2: rate.v1.RateService.GetRates:input_type -> rate.v1.GetRatesRequest
	3, // 3: rate.v1.RateService.HealthCheck:input_type -> rate.v1.HealthCheckRequest
	2, // 4: rate.v1.RateService.GetRates:output_type -> rate.v1.GetRatesResponse
	4, // 5: rate.v1.RateService.HealthCheck:output_type -> rate.v1.HealthCheckResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_rate_v1_rate_proto_init() }
func file_proto_rate_v1_rate_proto_init() {
	if File_proto_rate_v1_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rate_v1_rate_proto_rawDesc), len(file_proto_rate_v1_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rate_v1_rate_proto_goTypes,
		DependencyIndexes: file_proto_rate_v1_rate_proto_depIdxs,
		MessageInfos:      file_proto_rate_v1_rate_proto_msgTypes,
	}.Build()
	File_proto_rate_v1_rate_proto = out.File
	file_proto_rate_v1_rate_proto_goTypes = nil
	file_proto_rate_v1_rate_proto_depIdxs = nil
}
